containerPort: 8080

service:
  name: project-service-service

deployment:
  name: project-service-deployment
  replicas: 1
  image: nelsonjanusson/portfolio_project:project_service-latest

pod:
  name: project-service-pod