apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.grafana.httpRoute.name }}
  namespace: {{ .Values.grafana.httpRoute.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.grafana.httpRoute.pathPrefix }}
      backendRefs:
        - name: {{ .Values.grafana.service.name }}
          port: {{ .Values.grafana.containerPort }}