apiVersion: v1
data:
  username: {{ .Values.postgresql.cluster.owner }}
  password: {{ .Values.postgresql.secret.password }}
kind: Secret
metadata:
  name: {{ .Values.postgresql.secret.name }}
type: kubernetes.io/basic-auth
