apiVersion: v1
data:
  username: {{ .Values.postgresql.cluster.owner | b64enc }}
  password: {{ .Values.postgresql.secret.password | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.postgresql.secret.name }}
type: kubernetes.io/basic-auth
