apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.project-service.deployment.name }}
spec:
  replicas: {{ .Values.project-service.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.project-service.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.project-service.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.project-service.pod.name }}
        imagePullPolicy: Always
        image: {{ .Values.project-service.deployment.image }}
        ports:
        - containerPort: {{ .Values.project-service.containerPort }}