
projectService:
  containerPort: 8080
  service:
    name: project-service-service
  deployment:
    name: project-service-deployment
    replicas: 1
    image: nelsonjanusson/portfolio_project:project_service-latest
  pod:
    name: project-service-pod

frontend:
  containerPort: 5173
  service:
    name: frontend-service
  deployment:
    name: frontend-deployment
    replicas: 1
    image: nelsonjanusson/portfolio_project:portfolio_frontend-latest
  pod:
    name: frontend-pod
  httpRoute:
    name: frontend-httproute
    pathPrefix: /frontend


gateway:
  name: cilium-gateway
  gatewayClassName: cilium
  listener:  
    name: http-listener
    port: 8080
  
postgresql:
  cluster:
    name: postgresql-cluster
    instances: 2
    size: 1Gi
    database: appdata
    owner: baseuser
  secret:
    name: postgresql-secret
    password: aDHqf7ghloP=

grafana:
  containerPort: 80
  service:
    name: grafana
  httpRoute:
    name: grafana-httproute
    pathPrefix: /grafana
    namespace: monitoring
  
